<a href="https://colab.research.google.com/github/apothula/dl/blob/main/Intro/03_Numpy_Refresher_Part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 style="font-size:30px;">Numpy Refresher (Part-3)</h1>



<img src='https://learnopencv.com/wp-content/uploads/2022/01/c4_01_NumPy_logo.png' width=200 align='left'><br/>

## Table of Contents

* [1 Element-Wise Operations](#1-Element-Wise-Operations)
* [2 Linear Algebra](#2-Linear-Algebra)
* [3 Array Statistics](#3-Array-Statistics)

In [1]:
import numpy as np

def array_info(array):
    print('Array:\n{}'.format(array))
    print('Data type:\t{}'.format(array.dtype))
    print('Array shape:\t{}'.format(array.shape))
    print('Array Dim:\t{}\n'.format(array.ndim))

## 1 Element-Wise Operations


Let's generate two random arrays to demonstrate element-wise operations.

In [2]:
a = np.random.random((4,4))
b = np.random.random((4,4))
array_info(a)
array_info(b)

Array:
[[0.96048048 0.79703316 0.6368889  0.75846384]
 [0.29742858 0.85261992 0.12017932 0.23876994]
 [0.1669304  0.64370333 0.23394343 0.02657686]
 [0.78120517 0.89042081 0.51076749 0.51517809]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array:
[[0.16456288 0.04155845 0.73672301 0.48874162]
 [0.5581858  0.37232279 0.02502817 0.21800664]
 [0.52059724 0.5897348  0.45229838 0.83507151]
 [0.15872748 0.04618934 0.50586953 0.40653546]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2



### 1.1 Element-Wise Scalar Operations

### <font style="color:rgb(50,120,230)">Scalar Addition</font>

In [5]:
a + 5 # Element wise scalar addition.

array([[5.96048048, 5.79703316, 5.6368889 , 5.75846384],
       [5.29742858, 5.85261992, 5.12017932, 5.23876994],
       [5.1669304 , 5.64370333, 5.23394343, 5.02657686],
       [5.78120517, 5.89042081, 5.51076749, 5.51517809]])

### <font style="color:rgb(50,120,230)">Scalar Subtraction</font>

In [6]:
a - 5 # Element wise scalar subtraction.

array([[-4.03951952, -4.20296684, -4.3631111 , -4.24153616],
       [-4.70257142, -4.14738008, -4.87982068, -4.76123006],
       [-4.8330696 , -4.35629667, -4.76605657, -4.97342314],
       [-4.21879483, -4.10957919, -4.48923251, -4.48482191]])

### <font style="color:rgb(50,120,230)">Scalar Multiplication</font>

In [7]:
a * 10 # Element wise scalar multiplication.

array([[9.60480482, 7.97033159, 6.36888899, 7.58463837],
       [2.97428575, 8.52619923, 1.20179322, 2.38769944],
       [1.66930403, 6.43703326, 2.3394343 , 0.26576856],
       [7.81205172, 8.90420811, 5.1076749 , 5.15178092]])

### <font style="color:rgb(50,120,230)">Scalar Division</font>

In [8]:
a/10 # Element wise scalar division.

array([[0.09604805, 0.07970332, 0.06368889, 0.07584638],
       [0.02974286, 0.08526199, 0.01201793, 0.02387699],
       [0.01669304, 0.06437033, 0.02339434, 0.00265769],
       [0.07812052, 0.08904208, 0.05107675, 0.05151781]])

### 1.2 Element-Wise Array Operations

### <font style="color:rgb(50,120,230)">Array Addition</font>

In [ ]:
a + b # Element wise array/vector addition.

array([[1.1206598 , 1.14387814, 1.34375811, 0.98689985],
       [1.06845918, 0.54364916, 0.98807652, 1.26752561],
       [0.48539605, 0.74885733, 0.49049282, 0.460031  ],
       [0.75505558, 1.72672935, 1.38596673, 1.02731026]])

### <font style="color:rgb(50,120,230)">Array Subtraction</font>

In [ ]:
a - b # Element wise array/vector subtraction.

array([[-0.69983474,  0.63123864, -0.01396734,  0.90057351],
       [ 0.34610049,  0.19308814,  0.40839068, -0.26213814],
       [ 0.03924766,  0.29571156, -0.38553917, -0.34569407],
       [ 0.19745333, -0.12947929, -0.12271042,  0.31004143]])

### <font style="color:rgb(50,120,230)">Array Multiplication</font>

In [ ]:
a * b # Element wise array/vector multiplication.

array([[0.19152743, 0.22749875, 0.4513727 , 0.04073466],
       [0.25545487, 0.06456785, 0.20237806, 0.38447619],
       [0.05851724, 0.1183355 , 0.02298569, 0.02303103],
       [0.13278028, 0.74120734, 0.47646149, 0.23981017]])

### <font style="color:rgb(50,120,230)">Array Division</font>

In [ ]:
a / b # element wise array/vector division

array([[ 0.23115975,  3.46269995,  0.97942539, 21.8643983 ],
       [ 1.95825106,  2.10159499,  2.40900693,  0.65726044],
       [ 1.17593993,  2.30514978,  0.11980572,  0.14190564],
       [ 1.70822285,  0.86049058,  0.83732713,  1.86450552]])

Notice that the dimension of both arrays are equal in the above array element-wise operations. **What if the dimensions are not equal.** Let's check!

In [9]:
print('Array "a":')
array_info(a)
print('Array "c":')
c = np.random.rand(2, 4)
array_info(c)

# Should throw ValueError.
import traceback
try:
    a + c
except Exception:
    traceback.print_exc()

Array "a":
Array:
[[0.96048048 0.79703316 0.6368889  0.75846384]
 [0.29742858 0.85261992 0.12017932 0.23876994]
 [0.1669304  0.64370333 0.23394343 0.02657686]
 [0.78120517 0.89042081 0.51076749 0.51517809]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array "c":
Array:
[[0.3478699  0.44519556 0.91690017 0.79631405]
 [0.22512313 0.30767085 0.67328075 0.50588712]]
Data type:	float64
Array shape:	(2, 4)
Array Dim:	2



Traceback (most recent call last):
  File "<ipython-input-9-db3a8552b781>", line 10, in <cell line: 9>
    a + c
ValueError: operands could not be broadcast together with shapes (4,4) (2,4) 


<font color='red'>**Oh, got the ValueError!!**</font>

What is this error?

<font color='red'>ValueError</font>: operands could not be broadcast together with shapes `(4,4)` `(2,2)`

### 1.3 Broadcasting

There is a concept of broadcasting in NumPy, which tries to copy rows or columns in the lower-dimensional array to make an equal dimensional array of higher-dimensional array.

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Documentation: <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html" target=_blank>broadcasting</a>

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimensions and works its way left. Two dimensions are compatible when:

 - They are equal, or
 - One of them is 1

The examples below show how `B` is successfully broadcasted to `A` according to the rules above.

``` python
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
b = np.array([0, 1, 0])

print('Array "a":')
array_info(a)
print('Array "b":')
array_info(b)

print('Array "a+b":')
array_info(a + b)  # b is reshaped such that it can be added to a.

# b = [0,1,0] is broadcasted to     [[0, 1, 0],
#                                    [0, 1, 0],
#                                    [0, 1, 0]]  and added to a.

Array "a":
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int64
Array shape:	(3, 3)
Array Dim:	2

Array "b":
Array:
[0 1 0]
Data type:	int64
Array shape:	(3,)
Array Dim:	1

Array "a+b":
Array:
[[1 3 3]
 [4 6 6]
 [7 9 9]]
Data type:	int64
Array shape:	(3, 3)
Array Dim:	2



## 2 Linear Algebra

In this section, we will take a look at the most commonly used linear algebra operations used in machine learning.

## 2.1 Transpose

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Either syntax below can be used:

``` python
result = np.transpose(a, axes=None)

result = a.transpose(*axes)

result = a.T
```

Returns a view of the NumPy array `a` with axes transposed.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.transpose.html" target=_blank>np.transpose</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [11]:
a = np.random.random((2,3))
print('Array "a":')
array_info(a)

print('Transose of "a":')
a_transpose = a.transpose()  # Or a.T
array_info(a_transpose)

Array "a":
Array:
[[0.41254105 0.71510938 0.35266917]
 [0.05711373 0.72537597 0.63358695]]
Data type:	float64
Array shape:	(2, 3)
Array Dim:	2

Transose of "a":
Array:
[[0.41254105 0.05711373]
 [0.71510938 0.72537597]
 [0.35266917 0.63358695]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2



### 2.2 Matrix Multiplication
We will discuss two ways of performing matrix multiplication.

- `np.matmul`
- Python `@` operator

### <font style="color:rgb(50,120,230)">Using: `matmul`</font>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Using `matmul` is the most common approach for multiplying two matrices using Numpy. Multiplying two matrices requires that the number of columns of the first matrix, `M`, equals the number of rows in the second matrix, `N`, as shown below.

``` python
   M        N      
[p, q] x [q, r] = [p , r]
```
Documentation: <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html" target=_blank>np.matmul</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [ ]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
c = np.matmul(a,b)

print('matrix multiplication of a and b:')
array_info(c)

print('{} x {} --> {}'.format(a.shape, b.shape, c.shape)) # dim-1 of a and dim-0 of b has to be
                                                          # same for matrix multiplication

Array "a":
Array:
[[0.6558135  0.44199714 0.2873197  0.92405359]
 [0.3087299  0.18971711 0.75472795 0.29666377]
 [0.42034068 0.77374161 0.35020636 0.32808625]]
Data type:	float64
Array shape:	(3, 4)
Array Dim:	2

Array "b"
Array:
[[0.7266519  0.41308904]
 [0.26073966 0.53704643]
 [0.76897388 0.10513026]
 [0.55644044 0.62232665]]
Data type:	float64
Array shape:	(4, 2)
Array Dim:	2

matrix multiplication of a and b:
Array:
[[1.32691644 1.11355153]
 [1.01924774 0.49338635]
 [0.95904648 0.8301674 ]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2

(3, 4) x (4, 2) --> (3, 2)


### <font style="color:rgb(50,120,230)">Using: `@` operator</font>

This method of multiplication was introduced in Python 3.5. <a href="https://www.python.org/dev/peps/pep-0465/" target=_blank>See docs</a>.

In [12]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
c = a@b
array_info(c)

Array "a":
Array:
[[0.23565086 0.2623808  0.88179574 0.26596471]
 [0.91426254 0.87941457 0.91440019 0.85233351]
 [0.69489211 0.63049833 0.82867284 0.50937018]]
Data type:	float64
Array shape:	(3, 4)
Array Dim:	2

Array "b"
Array:
[[0.80546856 0.25430247]
 [0.28617241 0.8727737 ]
 [0.97984171 0.82089581]
 [0.01064348 0.11658368]]
Data type:	float64
Array shape:	(4, 2)
Array Dim:	2

Array:
[[1.13174654 1.04379523]
 [1.89311315 1.85002458]
 [1.55753466 1.46663345]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2



### 2.3 Matrix Inverse

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.linalg.inv(a)
```

For a square matrix, `a`, compute the (multiplicative) inverse of a matrix.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html?highlight=matrix%20inverse" target=_blank>np.linalg.inv</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [13]:
A = np.random.random((3,3))
print('Array "A":')
array_info(A)

A_inverse = np.linalg.inv(A)
print('Inverse of "A" ("A_inverse"):')
array_info(A_inverse)

print('"A x A_inverse = Identity" should be true:')
A_X_A_inverse = np.matmul(A, A_inverse)  # A x A_inverse = I = Identity matrix
array_info(A_X_A_inverse)

Array "A":
Array:
[[0.96737311 0.54136759 0.98693998]
 [0.0989966  0.64270848 0.41717809]
 [0.85624899 0.10826897 0.78085924]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2

Inverse of "A" ("A_inverse"):
Array:
[[ 7.51446778 -5.19741696 -6.72090422]
 [ 4.60555248 -1.47565638 -5.03265137]
 [-8.87854488  5.90381792  9.34822435]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2

"A x A_inverse = Identity" should be true:
Array:
[[ 1.00000000e+00 -4.08152300e-16  3.86153824e-16]
 [ 5.34829270e-16  1.00000000e+00 -1.94813282e-16]
 [ 1.67033801e-15 -3.26942804e-16  1.00000000e+00]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2



### 2.4 Dot Product

The dot product between two euqal length vectors is a scalar defined by the sum of the element-wise product of the two vectors.

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.dot(a, b, out=None)
```


Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.dot.html?highlight=dot%20product" target=_blank>np.dot</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

array_info(a)
array_info(b)

dot_prod = np.dot(a, b)
array_info(dot_prod)

Array:
[1 2 3 4]
Data type:	int64
Array shape:	(4,)
Array Dim:	1

Array:
[5 6 7 8]
Data type:	int64
Array shape:	(4,)
Array Dim:	1

Array:
70
Data type:	int64
Array shape:	()
Array Dim:	0



## 3 Array Statistics

### 3.1 Sum

In [15]:
a = np.array([1, 2, 3, 4, 5])

print(a.sum())

15


### 3.2 Sum Along Axis

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])
array_info(a)
print('')

print('sum along axis=0: ',a.sum(axis = 0)) # Sum along axis=0 ie: 1+4, 2+5, 3+6
print("")
print('sum along axis=1: ',a.sum(axis = 1)) # Sum along axis=1 ie: 1+2+3, 4+5+6

Array:
[[1 2 3]
 [4 5 6]]
Data type:	int64
Array shape:	(2, 3)
Array Dim:	2


sum along axis=0:  [5 7 9]

sum along axis=1:  [ 6 15]


### 3.3 Minimum and Maximum

In [17]:
a = np.array([-1.1, 2, 5, 100])

print('Minimum = ', a.min())
print('Maximum = ', a.max())

Minimum =  -1.1
Maximum =  100.0


### 3.4 Min and Max along Axis

In [ ]:
a = np.array([[-2, 0, 4], [1, 2, 3]])

array_info(a)

print('a =\n',a,'\n')
print('Minimum = ', a.min())
print('Maximum = ', a.max())
print()
print('Minimum along axis 0 = ', a.min(0))
print('Maximum along axis 0 = ', a.max(0))
print()
print('Minimum along axis 1 = ', a.min(1))
print('Maximum along axis 1 = ', a.max(1))

Array:
[[-2  0  4]
 [ 1  2  3]]
Data type:	int64
Array shape:	(2, 3)
Array Dim:	2

a =
 [[-2  0  4]
 [ 1  2  3]] 

Minimum =  -2
Maximum =  4

Minimum along axis 0 =  [-2  0  3]
Maximum along axis 0 =  [1 2 4]

Minimum along axis 1 =  [-2  1]
Maximum along axis 1 =  [4 3]


### 3.5 Mean and Standard Deviation

In [18]:
# Create some data.
data = np.array([1.2, 2.3, 5.0, 3.3, 1.4, 5.6])

print('Mean of the array               = {:8.6f}'.format(data.mean()))
print('Standard deviation of the array = {:8.6f}'.format(data.std()))

Mean of the array               = 3.133333
Standard deviation of the array = 1.684900


### 3.6 Standardizing an Array

Normalize the data array to have `mean=0` and `std=1`.

In [19]:
print('Array              = ', data)
print('Mean               = {:8.6f}'.format(data.mean()))
print('Standard deviation = {:8.6f}'.format(data.std()))
print()

standardized_array = (data - data.mean())/data.std()

print('Standardized Array = ', standardized_array)
print('Mean               = {:8.6f}'.format(standardized_array.mean()))
print('Standard deviation = {:8.6f}'.format(standardized_array.std()))

Array              =  [1.2 2.3 5.  3.3 1.4 5.6]
Mean               = 3.133333
Standard deviation = 1.684900

Standardized Array =  [-1.14744675 -0.49458912  1.10787962  0.09891782 -1.02874536  1.46398379]
Mean               = -0.000000
Standard deviation = 1.000000
