<a href="https://colab.research.google.com/github/apothula/dl/blob/main/Intro/05_Introduction_to_Tensorfow_Coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 style="font-size:30px;">TensorFlow Coding Basics</h1>

In this notebook, we will cover some of the essential TensorFlow operations that we will use throughout the course. TensorFlow has many analogous functions that are also contained in NumPy, and their usage is straightforward. However, there are a few things in TensorFlow that are unique to TensorFlow, and we will cover several examples in this notebook.


<img src='https://learnopencv.com/wp-content/uploads/2022/01/c4_01_TF_Logo.png' width=400 align='left'><br/>

## Table of Contents
* [1 TensorFlow Constants and Variables](#1-TensorFlow-Constants-and-Variables)
* [2 TensorFlow Reduce Functions](#2-TensorFlow-Reduce-Functions)
* [3 TensorFlow Indexing](#3-TensorFlow-Indexing)
* [4 NumPy / TensorFlow Interoperability](#4-NumPy-/-TensorFlow-Interoperability)

In [1]:
import tensorflow as tf
import numpy as np
import random
import matplotlib.pyplot as plt

In [ ]:
SEED_VALUE = 42

# Fix random number seed.
random.seed(SEED_VALUE)
np.random.seed(SEED_VALUE)
tf.random.set_seed(SEED_VALUE)

## 1 TensorFlow Constants and Variables

TensorFlow allows you to create both constants and variables. The key differece is that constants in TensorFlow are not mutable, while variables are. Also, an important distinction between NumPy and TensorFlow regarding variable assignment is that TensorFlow variables **require the use of the `assign()` method to change the value of a variable.**

### 1.1 TensorFlow Constants

In [2]:
rank_0_tensor = tf.constant(3)
print(rank_0_tensor)

rank_0_tensor = tf.constant(3.141592654)
print(rank_0_tensor)

rank_0_tensor = tf.constant(3.141592654, dtype=tf.float64)

print(rank_0_tensor)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.Tensor(3.141592654, shape=(), dtype=float64)


In [3]:
# Create a rank-1 constant in TensorFlow.
rank_1_tensor = tf.constant([2.0, 4.0, 6.0])
print(rank_1_tensor)

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)


In [4]:
# You can also explicitly define the datatype while creating the tensor.
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.int32)
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [5]:
# Create two constant tensors.
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [10, 11, 12]])

print(t1)
print('\n')
print(t2)
print('\n')

# Concatenate tensors along axis-0.
print(tf.concat([t1, t2], axis=0))
print('\n')

# Concatenate tensors along axis-1.
print(tf.concat([t1, t2], axis=1))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


### 1.2 TensorFlow Variables

The unique thing about TensorFlow variables is that you **cannot use the assignment (`=`) operator to assign a new value to a variable. You must use the `assign()` method as shown below.**

In [6]:
# Create a tensor variable.
tensor = tf.Variable([2, 4])

# Attempt to assign a new value to 0-th tensor element
try:
    tensor[0] = 11
    print('Tensor: ', tensor)
except TypeError:
    print("\nError: A tensor object does not support item assignment")


Error: A tensor object does not support item assignment


In TensorFlow, you can't change a tensor by left-hand assignment. Instead, you must use the `assign()` method as shown below.

In [7]:
# You must use the assign() method to assign a new value to a tensorflow variable
tensor[0].assign(42)
print(tensor[0])
print(tensor[1])

tf.Tensor(42, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


So, what is a `tf.Variable`? You can think of it as a wrapper around a tensor whose value can be changed by running operations on it. For more information, you can refer to the <a href="https://www.tensorflow.org/guide/variable" target=_blank>official documentation</a>.

## 2 TensorFlow Reduce Functions

There is a class of functions in TensorFlow that are used to compute various quantities of a tensor. Unlike NumPy, these functions start with the name 'reduce' (e.g., `reduce_sum()` instead of just `sum()`). This notation stems from the fact that these functions can compute a given quantity along any given axis of a tensor. If the axis is not specified, then the quantity is computed across all axes.

In [8]:
# Create some data.
x = 10 * tf.random.uniform(shape=[3,5])
print(x)

# Compute the following quantities for all axes..
xmin  = tf.reduce_min (x)
xmax  = tf.reduce_max (x)
xmean = tf.reduce_mean(x)
xsum  = tf.reduce_sum (x)

print('\nComputed over all axes:\n')
print('min:  ', xmin)
print('max:  ', xmax)
print('mean: ', xmean)
print('sum:  ', xsum)

# Compute the quantities for axis = 1.
xmin  = tf.reduce_min (x, axis=1)
xmax  = tf.reduce_max (x, axis=1)
xmean = tf.reduce_mean(x, axis=1)
xsum  = tf.reduce_sum (x, axis=1)

print('\nComputed for axis 1:\n')
print('min:  ', xmin)
print('max:  ', xmax)
print('mean: ', xmean)
print('sum:  ', xsum)

tf.Tensor(
[[1.8982744  7.933035   8.742671   7.216103   8.869612  ]
 [5.2791224  5.4846535  0.17470479 7.8072977  2.907052  ]
 [0.68398595 1.3725841  3.6243725  2.154994   4.442382  ]], shape=(3, 5), dtype=float32)

Computed over all axes:

min:   tf.Tensor(0.17470479, shape=(), dtype=float32)
max:   tf.Tensor(8.869612, shape=(), dtype=float32)
mean:  tf.Tensor(4.572723, shape=(), dtype=float32)
sum:   tf.Tensor(68.59084, shape=(), dtype=float32)

Computed for axis 1:

min:   tf.Tensor([1.8982744  0.17470479 0.68398595], shape=(3,), dtype=float32)
max:   tf.Tensor([8.869612  7.8072977 4.442382 ], shape=(3,), dtype=float32)
mean:  tf.Tensor([6.931939  4.3305655 2.4556637], shape=(3,), dtype=float32)
sum:   tf.Tensor([34.659695 21.652828 12.278318], shape=(3,), dtype=float32)


## 3 TensorFlow Indexing (`gather`)

### <font style="color:rgb(50,120,230)">NumPy array indexing</font>

Let's first review how NumPy arrays can be easily indexed using another NumPy array.

In [9]:
# Create some data.
num_data = 24
data = np.random.uniform(0, 10, num_data)
print('data: \n', data)
print('\n')

# Create an array of random indices.
indices = np.random.choice(data.shape[0], 5, replace=False)
print('indices: ', indices)
print('\n')

# Use the indices array to select the corresponding elements from the data array.
selected_data = data[indices]

print('selected_data: ', selected_data)

data: 
 [0.2360677  9.4672592  2.0466176  0.81317357 2.40116483 3.90444095
 7.96771022 9.01344535 8.3991912  9.50064372 0.70736823 4.44536351
 9.05685944 4.07841174 4.08533157 2.39678333 1.31638888 9.29003296
 3.59082955 9.39940199 0.57286515 4.73113405 4.0891882  9.59812757]


indices:  [16  1  2 20  8]


selected_data:  [1.31638888 9.4672592  2.0466176  0.57286515 8.3991912 ]


### <font style="color:rgb(50,120,230)">TensorFlow array indexing</font>

When using TensorFlow variables, we need to make use of the `tf.gather()` method to achieve the functionality as shown above in NumPy.

In [10]:
# Create some data.
num_data = 24
data = tf.random.uniform(shape=[num_data])
print('data: \n', data)
print('\n')

# Create an array of random indices.
indices = tf.random.uniform([5], minval=0, maxval=len(data)-1, dtype=tf.dtypes.int32)
print('indices: ', indices)
print('\n')

# Use this he gather() method to index one tensor by another tensor.
selected_data = tf.gather(data, indices)

print('selected_data: ', selected_data)

data: 
 tf.Tensor(
[0.9633695  0.2868538  0.08474123 0.01512766 0.52788687 0.73247457
 0.03248    0.8645699  0.4877963  0.47930264 0.8005067  0.68605363
 0.5921929  0.9916985  0.16226256 0.65381205 0.06260777 0.79169464
 0.9800712  0.6271751  0.12256014 0.69193697 0.2422471  0.12033153], shape=(24,), dtype=float32)


indices:  tf.Tensor([17 22 16  5 12], shape=(5,), dtype=int32)


selected_data:  tf.Tensor([0.79169464 0.2422471  0.06260777 0.73247457 0.5921929 ], shape=(5,), dtype=float32)


Let's now assume we have a rank-2 tensor and would like to select specific rows within the tensor. This can easily be accomplished with the `gather()` method where we specify a list of the row indices and also specify the axis along which those indices are applied.

In [11]:
# Create a random tensor.
tensor = tf.random.normal(shape=[5, 3])
print(tensor)
print('\n')

# Create a tensor with indices.
rows = tf.constant([0, 2, 4])
cols = tf.constant([0, 2])

print('1st, 3rd, and 5th rows:')

# Access specific rows of a tensor by specifying the
# indices of the rows along with the row axis.
print(tf.gather(tensor, rows, axis=0))

print('\n')
print('1st and 3rd, cols:')

# Access specific cols of a tensor by specifying the
# indices of the cols along with the col axis.
print(tf.gather(tensor, cols, axis=1))

tf.Tensor(
[[ 0.09861331 -1.7489804   1.0942632 ]
 [ 0.6195667   0.93154454 -0.091554  ]
 [ 0.03943091  0.11199389 -0.07747791]
 [-0.00733635 -0.41640306 -0.024058  ]
 [-0.39752242  0.10444986 -0.65109706]], shape=(5, 3), dtype=float32)


1st, 3rd, and 5th rows:
tf.Tensor(
[[ 0.09861331 -1.7489804   1.0942632 ]
 [ 0.03943091  0.11199389 -0.07747791]
 [-0.39752242  0.10444986 -0.65109706]], shape=(3, 3), dtype=float32)


1st and 3rd, cols:
tf.Tensor(
[[ 0.09861331  1.0942632 ]
 [ 0.6195667  -0.091554  ]
 [ 0.03943091 -0.07747791]
 [-0.00733635 -0.024058  ]
 [-0.39752242 -0.65109706]], shape=(5, 2), dtype=float32)


## 4 NumPy / TensorFlow Interoperability

When using TensorFlow it is very common to also make use of NumPy, and it is very common to convert between NumPy and Tensor Flow variables in code you are developing. In this section, we will demonstrate the use of several built-in functions that allow you to convert back and forth between and NumPy and TensorFlow.

- `tf.convert_to_tensor(python_object)`
- `tensor.numpy()`

In [12]:
# Create a python list.
python_list = [1, 2]

# Create a NumPy array from the list.
numpy_array = np.array(python_list)

# Create a tensor from list.
tensor_from_list = tf.convert_to_tensor(python_list)

# Create a tensor from a NumPy array.
tensor_from_array = tf.convert_to_tensor(numpy_array)

# Create a NumPy array from a tensor.
array_from_tensor = tensor_from_array.numpy()

print('List:   ', python_list)
print('Array:  ', numpy_array)
print('Tensor: ', tensor_from_list)
print('Tensor: ', tensor_from_array)
print('Array:  ', array_from_tensor)

List:    [1, 2]
Array:   [1 2]
Tensor:  tf.Tensor([1 2], shape=(2,), dtype=int32)
Tensor:  tf.Tensor([1 2], shape=(2,), dtype=int64)
Array:   [1 2]
